<?php

namespace Antidote\LaravelCart\Tests;

use Antidote\LaravelCart\Tests\laravel\app\Models\TestStripeOrder;
use Antidote\LaravelCart\Tests\laravel\app\Models\TestStripeOrderLogItem;
use Illuminate\Support\Facades\Config;

class StripeTestCase extends TestCase
{
    protected function migrateUsing()
    {
        return [
            '--path' => [
                './database/migrations/stripe'
            ]
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        Config::set('laravel-cart.classes.order', TestStripeOrder::class);
        Config::set('laravel-cart.classes.order_log_item', TestStripeOrderLogItem::class);
    }
}
